### PR TITLE
Adds Metric Tracking using Google Analytics

### PR DESCRIPTION
**Pull request by DanielJMaher**

### CODE REVIEW

**Comment by FBRTMaka** [comment]
@DanielJMaher we want to put the google analytics account ID in github?

**Comment by DanielJMaher** [comment]
@FBRTMaka Yea, this is a junk account that i don't care about.  it doesn't hold any importance.  I can delete it if it gets abused.  

I would never put the official OOI GA tracking code.  That would be a bad time.

**Comment by FBRTMaka** [comment]
@DanielJMaher That's cool...as for this approach it seems that doing it at the app level may be better.  Take a look at this for an idea: https://github.com/citruspi/Flask-Analytics

This will save the terrible terrible task of manually updating each URL.  Also, the config variable could be set as an environment variable so it's plug and play.

**Comment by FBRTMaka** [comment]
Not saying that's THE solution, but just the approach may be simpler.

**Comment by DanielJMaher** [comment]
@FBRTMaka I'm afraid that it would flood the GA account.  I only put it in for the pages I want to track.  If we did it on the app level wouldn't it hit for EVERY page?

**Comment by FBRTMaka** [comment]
@DanielJMaher Well that's the idea, and GA is quite capable of handling it.  There are far bigger sites than ours that use it on every page.

**Comment by DanielJMaher** [comment]
@FBRTMaka I'm not worried about GA not handling it, I'm worried about reading the results.  Either rate, i'm going to leave it this way for now and get some feedback on the metrics from Rutgers and COL.  If they want more data, I'll look into doing it at the app level.

**Comment by FBRTMaka** [comment]
Cool beans.

**Comment by DanielJMaher** [comment]
@oceanzus Review and merge if you agree??? Also, note the change to the config file for deployments

**Comment by DanielJMaher** [comment]
ANYONE?

**Pull request merged**
