### PR TITLE
changed design of close button on map popups

### PR DESCRIPTION
**Pull request by dlangston**

### CODE REVIEW

**Comment by dlangston** [comment]
New buttons....

screen shot 2015-08-12 at 9 56 44 am
screen shot 2015-08-12 at 9 56 54 am
screen shot 2015-08-12 at 9 56 58 am

**Comment by birdage** [comment]
@dlangston the top image header has a weird boarder, should it have round corners on the bottom? the rest look great, @DanielJMaher FYI

**Comment by dlangston** [comment]
your right let me change that

**Comment by dlangston** [comment]
@birdage

**Comment by DanielJMaher** [comment]
@birdage Merge when you are happy.

**Comment by dlangston** [comment]
@birdage that should look better now

screen shot 2015-08-12 at 10 16 59 am

**Pull request merged**
