### PR TITLE
Mc toc rework

### PR DESCRIPTION
**Pull request by FBRTMaka**
@DanielJMaher , @birdage , @Bobfrat ,

Phew!

### CODE REVIEW

**Comment by birdage** [comment]
@FBRTMaka going to merge in a few minutes, looking good!

**Comment by birdage** [comment]
@FBRTMaka can you resolve the merge issues for me pls

**Comment by FBRTMaka** [comment]
@birdage easy peasy!

**Comment by birdage** [comment]
:+1: merging!

**Comment by FBRTMaka** [comment]
shit

**Comment by FBRTMaka** [comment]
lol guess it's ready! haha

**Comment by Bobfrat** [comment]
does navigating to a stream through the URL still work? ie http://localhost:5000/plotting/CP/CP01CNSM/RID26

**Comment by FBRTMaka** [comment]
@Bobfrat , no but that's in the works  - also, I need to limit navigating to a stream directly only when the URL is a stream (that's a assembly I think).  BUT, when someone gets a link like that it will open out the TOC to that platform/assembly and you can then choose what instrument you want.

**Pull request merged**
