### PR TITLE
Update status

### PR DESCRIPTION
**Pull request by birdage**
DO NOT MERGE YET, IN PROGRESS

screen shot 2015-09-17 at 4 44 04 pm
screen shot 2015-09-17 at 4 44 16 pm

### CODE REVIEW

**Comment by birdage** [comment]
@FBRTMaka we need to chat about the asset information and how to update it when your back

**Comment by FBRTMaka** [comment]
@birdage , YEAH we do! I'll see you tomorrow!

**Comment by birdage** [comment]
@FBRTMaka how goes it?

**Comment by FBRTMaka** [comment]
@birdage goes well, how things on your side?

**Comment by DanielJMaher** [comment]
@birdage WHere are we here?

**Comment by birdage** [comment]
@DanielJMaher services need to be merged first

**Comment by FBRTMaka** [comment]
Ok, I see the comment about the services merge and it looks like this is ready.

**Pull request merged**
