### PR TITLE
Pioneer array

### PR DESCRIPTION
**Pull request by dlangston**
code clean up

### CODE REVIEW

**Comment by oceanzus** [comment]
Looks like a rebase against master is required before this can be merged.

**Comment by DanielJMaher** [comment]
@dlangston You heard the man!  DO you know how to do that?

**Comment by oceanzus** [comment]
Also, please change the names of files that have spaces in them to keep with our naming conventions.

**Comment by oceanzus** [comment]
Added to hotfix for release 3 here:
https://github.com/asascience-open/ooi-ui/pull/261

**Pull request closed without merging**
