### PR TITLE
changes redmine page to direct users to a static helpdesk email for a…

### PR DESCRIPTION
**Pull request by FBRTMaka**
…ll issues

@DanielJMaher

### CODE REVIEW

**Comment by DanielJMaher** [comment]
@FBRTMaka Screen Cap?  Or should I walk over?

**Comment by DanielJMaher** [comment]
@FBRTMaka Also, can you add a link to the Red Mine?  That is desired.

**Comment by FBRTMaka** [comment]
@DanielJMaher Sure, what's the URL they want?

**Comment by FBRTMaka** [comment]
@DanielJMaher 
screen shot 2015-11-30 at 11 05 01 am

**Pull request merged**
