### PR TITLE
Update subscription

### PR DESCRIPTION
**Pull request by birdage**
@FBRTMaka @DanielJMaher

### CODE REVIEW

**Comment by birdage** [comment]
hold on this for now till we iron out a few things

**Comment by birdage** [comment]
@FBRTMaka any updates on the user verification piece?

**Comment by DanielJMaher** [comment]
@FBRTMaka Is this good to go?

**Comment by birdage** [comment]
@DanielJMaher @FBRTMaka good for second review

**Comment by FBRTMaka** [comment]
@birdage looking good mate!

**Pull request merged**
