### PR TITLE
Adds Alerts and Alarms, Glossary, FAQ and Fixes Trouble Ticket html

### PR DESCRIPTION
**Pull request by brian-smith723**
Cannot be logged in to access Alerts and Alarms.
TroubleTicket requires changes to services to be operational-- will make a pull request.

### CODE REVIEW

**Comment by DanielJMaher** [comment]
@brian-smith723 I thought you were going to create separate pull requests for the FAQ/Glossary and the Alerts/Alarms.  I don't want to merge in the Alerts/Alarms yet, only the Glossary/FAQ.  I am going to deny the merge.

**Comment by brian-smith723** [comment]
Sorry. Want me to make a pull request for Trouble Tickets page, glossay and faq ?

**Comment by DanielJMaher** [comment]
Can you make a PR for just the FAQ and Glossary?

**Comment by brian-smith723** [comment]
ok

**Pull request closed without merging**
