### PR TITLE
Remove time from plotting parameters

### PR DESCRIPTION
**Pull request by Bobfrat**
@FBRTMaka 
Is this going to affect anything outside of plotting?

### CODE REVIEW

**Comment by DanielJMaher** [comment]
@FBRTMaka @Bobfrat Gut reaction says it will stop someone from finding metadata using the TOC, but it would still be shown in the Data Catalog.

**Comment by FBRTMaka** [comment]
@Bobfrat @DanielJMaher , it won't - time isn't used for anything but the plotting page's controls at the moment.

**Comment by DanielJMaher** [comment]
@Bobfrat @FBRTMaka I was confused on what this PR was.  My bad.

**Comment by FBRTMaka** [comment]
@DanielJMaher , we still <3 you.

**Pull request merged**
