### PR TITLE
Mc assets page

### PR DESCRIPTION
**Pull request by FBRTMaka**
@DanielJMaher , @ssontag55 ,

Several of sontag's checked are left out for now, and will be reworked back in.  Otherwise, this is a rework to get the assets page more modular and follow the MVC pattern.

### CODE REVIEW

**Comment by ssontag55** [comment]
Ouch.  It's gonna be tricky getting in all that existing functionality

**Comment by DanielJMaher** [comment]
@ssontag55 How so?

**Comment by ssontag55** [comment]
Looks like the coordinate conversion, bootstrap date field objects and some of the search table and sorting was taken out. I'd have to look closer. 

Stephen

**Comment by DanielJMaher** [comment]
@FBRTMaka @ssontag55 I believe that this is going to be fine.  We are having to change our underlying data structure, which will enable us to improve our filtering and searching.  There is some work to come for that, which Matt will be tasked with.

@FBRTMaka Can you think about Sontag's concerns and make sure we aren't blowing anything up?

**Comment by FBRTMaka** [comment]
@ssontag55 , yeah the conversion for entering lat/lon was taken out but will be going back in when field validation happens.  However, there is already a conversion that happens in the services which will keep the rendering of the lat/lon how we want it.  

The date picker was left out because of the inconsistencies in the date format.  Ideally, the services will return the date in one format, no matter what.  When that happens, implementing a solid date picker will be much easier.  

The searching is optimized with an elastic search to the services, and with the changes to the search and filtering in general the filtering was left out (and may not actually make a reappearance in the way it was originally implemented).

**Pull request merged**
