### PR TITLE
very very slight TOC load time enhancement...very slight

### PR DESCRIPTION
**Pull request by FBRTMaka**
@DanielJMaher , this console.log was stalling the TOC too much - by about a second.

@Bobfrat , when you get a chance can you review that code change (I'm totally tolling you right now).

@birdage , could you just verify the order of loading for the TOC still makes sense, even though the fetch is outside the TOC load chain?

### CODE REVIEW

**Comment by birdage** [comment]
@FBRTMaka looks ok, and it tested ok

**Comment by birdage** [comment]
@FBRTMaka merge mine first?

**Comment by FBRTMaka** [comment]
@birdage , yes, yours is WAYY more important - I'm reviewing it now

**Comment by DanielJMaher** [comment]
@birdage Can you okay this for merge so i can bounce casadev

**Pull request merged**
