### PR TITLE
Filter icon

### PR DESCRIPTION
**Pull request by dlangston**

### CODE REVIEW

**Comment by birdage** [comment]
@dlangston why is there a function in the partial? this should be in the view, looking at the function this shouldn't this just be something like `<i class="fa fa-filter"></i>`?

**Comment by birdage** [comment]
@dlangston can you squash the commits to one please as i want to keep the commit history clean when i merge

**Comment by birdage** [comment]
@dlangston status?

**Comment by DanielJMaher** [comment]
@dlangston We need to get this in before 1130.  Ping

**Comment by birdage** [comment]
@dlangston @dlangston i cant merge this till the partial is fixed, even if we dont squash those commits.

**Pull request closed without merging**
