### PR TITLE
Mc platform map

### PR DESCRIPTION
**Pull request by maka-io**
@DanielJMaher , Here are the platforms on the platform map, and consolidated instrument assemblies.

### CODE REVIEW

**Comment by maka-io** [comment]
@DanielJMaher here's the fix for the duplicate instruments

**Comment by DanielJMaher** [comment]
@maka-io looks phenomenal.  Great job man.  Will merge once we make sure it doesn't confuddle Jim's PR

**Comment by DanielJMaher** [comment]
@maka-io Do you have the new images for this PR as well?  Per https://uframe-cm.ooi.rutgers.edu/issues/10516

**Comment by maka-io** [comment]
@DanielJMaher Here's the updated vector map

**Comment by DanielJMaher** [comment]
@maka-io Vector? Not Tile?

**Pull request closed without merging**
