### PR TITLE
added "dynamic" query table for assets

### PR DESCRIPTION
**Pull request by ssontag55**
DO NOT MERGE.

Update for semi-dynamic query options for assets (and other tables) can, add to status page if you like?  :)

Also added table export to csv, json, text file ect.

(remove backgrid)

multifilter
filter_optins
export

### CODE REVIEW

**Comment by oceanzus** [comment]
Looks nice!

**Comment by DanielJMaher** [comment]
The Export Feature!  So Smart!

**Comment by DanielJMaher** [comment]
And yea, add to status page!

**Comment by DanielJMaher** [comment]
@ssontag55 Let me know when this is Good to go

**Comment by ssontag55** [comment]
@DanielJMaher asset management page is done, working on status page now

**Comment by ssontag55** [comment]
It's not perfect since the Assets JSON is kinda messed up, but ready to go.

@oceanzus @DanielJMaher  

status_filter

 @birdage I added the map icon and the function in the /js/views/common/StatusUIIconView.js file for you to do what you want.

**Comment by DanielJMaher** [comment]
@ssontag55 This works for the List View on the status page as well?

**Comment by ssontag55** [comment]
@DanielJMaher  Yes sir.

**Pull request merged**
