### PR TITLE
event-scroll squashed

### PR DESCRIPTION
**Pull request by dlangston**
fixed MC in bower file

merge commit #2

rearanged css

removed unneeded css code

removed unneeded css code

removed unneeded css code

scoll working with proper image size using max-height

moded styles to css removed unneeded code and console log

added id to stickyTableHeader for events

fixed error in code that resulted from merge conflict and spacing

### CODE REVIEW

**Comment by dlangston** [comment]
@birdage This replaces PR #473

**Comment by DanielJMaher** [comment]
@dlangston Merge Conflict.   Fix.

**Comment by birdage** [comment]
@DanielJMaher @dlangston can this be closed?

**Comment by dlangston** [comment]
Yes

**Pull request closed without merging**
