### PR TITLE
BUG: Workaround to prevent all assets from being loaded under instrument...

### PR DESCRIPTION
**Pull request by FBRTMaka**
Workaround to prevent all assets from being loaded under instrument list is to not render instrument list.  This will need to be backtracked so a better solution can be found.

@DanielJMaher , @Sontag?, @birdage 
Ln: 258 is the comment.  All other changes are white space removal, sorry about that.

### CODE REVIEW

**Comment by oceanzus** [comment]
There are a bunch of un-terminated (missing semicolon) lines in this file as well.

**Comment by FBRTMaka** [comment]
I don't see any, which lines?

**Comment by oceanzus** [comment]
233-236, 253 for instance

**Comment by FBRTMaka** [comment]
lol

**Comment by FBRTMaka** [comment]
I was like looking at a black counter top and seeing one ant...then you see ALL the ants.

**Comment by DanielJMaher** [comment]
@FBRTMaka @oceanzus So this doesnt get merged yet?  Does it get closed?

**Comment by FBRTMaka** [comment]
null issue once TOC is done...

**Pull request closed without merging**
