### PR TITLE
Check for scopes in dropdown.

### PR DESCRIPTION
**Pull request by RyanMaciel**
Checks for the users scopes in the navbar and only shows ui that is available to them.

### CODE REVIEW

**Comment by DanielJMaher** [comment]
@FBRTMaka This will get tested and moved in with your next PR.

**Comment by FBRTMaka** [comment]
@DanielJMaher , we should keep this in it's own PR.  It'll be easier to keep track if we need to come back to it later.

**Comment by DanielJMaher** [comment]
@FBRTMaka I meant that we aren't rebaselining our code until your PR is in at which point we will review this and merge it in as it's own PR.

**Comment by FBRTMaka** [comment]
@DanielJMaher, I'll actually need this in before my PR since the hiding of the menu items is something I'll need.

**Pull request merged**
