### PR TITLE
Update trouble tickets

### PR DESCRIPTION
**Pull request by Bobfrat**
@DanielJMaher this makes Sage the assignee and removes all the unneeded buttons.

related to https://github.com/asascience-open/ooi-ui-services/pull/386

### CODE REVIEW

**Comment by DanielJMaher** [comment]
@birdage Review please.   I think it does what we want, i just want to make sure his practices were right.

**Comment by DanielJMaher** [comment]
@birdage Do Not Merge Yet
More coming in

**Comment by DanielJMaher** [comment]
@Birdage Darn

**Comment by DanielJMaher** [comment]
@Bobfrat Too Late.  Make it a new PR

@birdage No Worries Birdie

**Comment by birdage** [comment]
@DanielJMaher lol

**Comment by DanielJMaher** [comment]
@birdage Too Fast

**Pull request merged**
