### PR TITLE
Mc event pane

### PR DESCRIPTION
**Pull request by FBRTMaka**
@DanielJMaher , @ssontag55 

Update asset management page, with event pane.

TODO: Consolate duplicate code into a function, just wanted to get this bit in here asap.

### CODE REVIEW

**Comment by DanielJMaher** [comment]
@FBRTMaka how long would it take to consolodate that code?

**Comment by FBRTMaka** [comment]
Another hour or so, should be ready by noon

**Comment by FBRTMaka** [comment]
@DanielJMaher good to go!

**Comment by DanielJMaher** [comment]
@ssontag55 Can you review please?

**Pull request merged**
