### PR TITLE
Dynamic Filter, Search and Sort

### PR DESCRIPTION
**Pull request by ssontag55**
In progress..

Sorting on columns 
Dynamic field search updated after each table query is done -- in progress

Tested on uframe-test.ooi

### CODE REVIEW

**Comment by DanielJMaher** [comment]
@FBRTMaka Is this getting on top of your toes??

**Comment by ssontag55** [comment]
@DanielJMaher @FBRTMaka ... the only thing on the asset page that changed is the column Object:
https://github.com/ssontag55/ooi-ui/blob/filter/ooiui/static/js/views/asset_management/AssetView.js#L63

Let me know if it's an issue

**Comment by FBRTMaka** [comment]
@DanielJMaher yeah, that asset page changes are still going to conflict terribly.  The entire file is broken up into 5 small view classes.  So it won't merge at all.

**Comment by ssontag55** [comment]
That column object should only be in one view.

**Comment by FBRTMaka** [comment]
It what you have it's in 1 of 1, in what I have it would be in 1 of 5.

**Comment by DanielJMaher** [comment]
@ssontag55 Matt has been reworking the asset page to break each asset item in the table into it's own view.  This allows for us to update a single asset without having to reload everything.  

No work can be merged into the AM page until after he is done otherwise we face the wrath of the merge conflict!

**Comment by ssontag55** [comment]
@FBRTMaka let me know if you need any help merging the column stuff

**Pull request closed without merging**
