### PR TITLE
add camera image page

### PR DESCRIPTION
**Pull request by birdage**
@DanielJMaher as discussed, <b>do not merge yet</b>, requires services

screen shot 2015-12-29 at 4 10 14 pm

### CODE REVIEW

**Comment by FBRTMaka** [comment]
Saw this on FF:
screen shot 2016-01-05 at 10 55 37 am

**Comment by DanielJMaher** [comment]
How did that happen?  @birdage @FBRTMaka 

We arent loading new code until tonight, so if this can get some love before COB that would be great!

**Comment by birdage** [comment]
@FBRTMaka did you grunt and open in an incognito window? if so it looks like a `z-index` issue, and would be very easy to fix, maybe some of the css for the bitdash player changed, and it looks like they updated their player slightly.

@DanielJMaher FYI

**Comment by FBRTMaka** [comment]
@birdage grunted yes, but an incognito window shouldn't be a requirement :P

**Comment by birdage** [comment]
@FBRTMaka it isnt, but its a good first check for verifying changes in css, if your using your local machine

**Comment by FBRTMaka** [comment]
@birdage did I mention this is in FF?

**Comment by birdage** [comment]
@FBRTMaka theres a similar option in firefox, it all depends on your browser caching settings, and if css is cached. i sometimes have that issue in chrome, so the solution is a hard refresh (clear page cache and reload) or a like `incognito` window.

**Comment by FBRTMaka** [comment]
screen shot 2016-01-05 at 12 32 40 pm

**Comment by DanielJMaher** [comment]
@FBRTMaka is Andy's diagnosis agreeable?  or is something wrong?

**Comment by FBRTMaka** [comment]
@DanielJMaher naw, he's just juking the problem coming in lol  
CSS caching isn't the issue here.

**Comment by birdage** [comment]
@FBRTMaka verifying its not that before i look at it.

**Comment by DanielJMaher** [comment]
@FBRTMaka What are the steps to recreate?

**Comment by FBRTMaka** [comment]
@DanielJMaher , @birdage , 
1. Open FireFox, open http://localhost:5000/cameras
2. Click on a thumbnail below.
3. View result.

**Comment by FBRTMaka** [comment]
@birdage Boom! killed it! :+1:

**Pull request merged**
