### PR TITLE
Adds phone number validation to new user registration

### PR DESCRIPTION
**Pull request by benjwadams**
Checks for a US phone number on the primary and secondary phone fields.
Also check to make sure they aren't starting with invalid numbers for
an individual person such as 911 or 0.

### CODE REVIEW

**Comment by DanielJMaher** [comment]
@benjwadams Can you add to the form an example acceptable format?  Similar to this: 
image

**Comment by DanielJMaher** [comment]
@benjwadams ??? Are you doing this?

**Comment by benjwadams** [comment]
Ok, but can we create a separate issue on Redmine for this? It's somewhat separate from the original task of validating the phone numbers

**Comment by benjwadams** [comment]
Scratch that.  We may want to add some extra input placeholder to the form down the road along with indicating which fields are required.

**Comment by benjwadams** [comment]
Hold off on merging this.  The need for Backbone.Validation appears to break the user edit form.  Looking into the issue.

**Pull request merged**
