### PR TITLE
Data catalog url search population

### PR DESCRIPTION
**Pull request by dlangston**

### CODE REVIEW

**Comment by birdage** [comment]
@dlangston can you squash the commits to one please as i want to keep the commit history clean when i merge

**Comment by birdage** [comment]
@dlangston status?

**Comment by DanielJMaher** [comment]
@birdage If he doesn't get this squash to work soon can we just move forward.  i dont want to spend too much time.

**Comment by birdage** [comment]
@dlangston any updates or am i merging?

**Pull request closed without merging**
