### PR TITLE
changed width of instrument popup bottom scroll to auto to prevent gap

### PR DESCRIPTION
**Pull request by dlangston**
@FBRTMaka @DanielJMaher @birdage 
changed the width to auto to remove the gap. 
screen shot 2015-10-02 at 11 05 55 am

Also, I think we should ether add or remove some styling to the scroll bars so they match, and maybe add a sticky-header to the middle scrollable area so that the header doesn't scroll away when you scroll down the list.

### CODE REVIEW

**Comment by birdage** [comment]
@dlangston wanna fix the style of the scroll bars in this pull request pls

**Comment by dlangston** [comment]
@birdage sure

**Comment by birdage** [comment]
@dlangston status?

**Comment by dlangston** [comment]
@birdage  Working on it now. Matt is having me add some other features to the popup.

**Comment by DanielJMaher** [comment]
@dlangston Let me know when it is good.

**Comment by FBRTMaka** [comment]
@dlangston thanks!

**Comment by dlangston** [comment]
@FBRTMaka

**Comment by DanielJMaher** [comment]
@birdage Are we G2G here?

**Comment by FBRTMaka** [comment]
@DanielJMaher , @dlangston closing this in lieu of PR in branch

**Pull request closed without merging**
