### PR TITLE
Adds initial workflow changes to A&A.

### PR DESCRIPTION
**Pull request by oceanzus**
Requires user and user_event_notification model hookups still.

DO NOT MERGE YET

### CODE REVIEW

**Comment by oceanzus** [comment]
@DanielJMaher @birdage https://github.com/asascience-open/ooi-ui-services/pull/402 may have an impact on this PR, so let's try to get 402 reviewed and merged as soon as possible.

**Comment by oceanzus** [comment]
@DanielJMaher @birdage Waiting on a couple services changes from @ednad tomorrow before this can be finalized.

**Comment by birdage** [comment]
@oceanzus shall i wait on reviewing this then?

**Comment by oceanzus** [comment]
@birdage Yes, please wait.

**Comment by oceanzus** [comment]
@birdage This is ready, but relies on https://github.com/asascience-open/ooi-ui-services/pull/408

**Comment by FBRTMaka** [comment]
@oceanzus is the TOC hooked up at all in either the aa or triggered aa pages?  If it's not, @DanielJMaher do you think we should remove it?

**Comment by oceanzus** [comment]
@FBRTMaka Yes, the TOC is required for the A&A definition page in order to select the instrument to create a def against.  It is not used in the trigger A&A page.  @DanielJMaher make a call ASAP so I can make changes if you want them.

**Comment by FBRTMaka** [comment]
@oceanzus , that's cool - just wanted to be sure it was being used.  I'm going to merge this

**Pull request merged**
