### PR TITLE
OpLogs Search Functionalityode

### PR DESCRIPTION
**Pull request by c0mster**
Code functionality to search OpLogs by title, description, user, daterange and oplog comments.
@DanielJMaher  Please test and report any issues, thanks

### CODE REVIEW

**Comment by birdage** [comment]
@c0mster in a holding pattern on this one

**Comment by birdage** [comment]
@FBRTMaka hold on this, by order of @DanielJMaher

**Comment by FBRTMaka** [comment]
@DanielJMaher , @birdage , @c0mster : Heard that Andy!

**Comment by DanielJMaher** [comment]
@c0mster Are we confident here?  Should we not have merged that backend?

**Comment by c0mster** [comment]
@DanielJMaher This should be all ready to go now. The service as well needs to be merged and uploaded to the test server.

Please let me know if there are any issues.

Thanks

**Comment by FBRTMaka** [comment]
:+1: sweet @c0mster !!

**Comment by FBRTMaka** [comment]
@c0mster , @DanielJMaher , I'm going to merge this when I get in.  @c0mster , I noticed that the popup to make a log/comment has a placeholder as the value="" attribute.  It's not a BIG deal, bit it should be changed to the placeholder="" attribute so a user doesn't have to delete the text to write in their text.

If you can get it in, awesome, otherwise maybe for a future PR?

**Comment by FBRTMaka** [comment]
@c0mster lets take a stab at it a bit later, it's good for now!

**Comment by FBRTMaka** [comment]
@c0mster , we'll do this placeholder thing later ;)

**Pull request merged**
