### PR TITLE
update level toc code to fix parse error on toc item

### PR DESCRIPTION
**Pull request by birdage**
@DanielJMaher @FBRTMaka @oceanzus update to fix the toc list

screen shot 2015-06-16 at 11 29 52 am

### CODE REVIEW

**Comment by birdage** [comment]
added a try catch for random platform names that dont conform

**Comment by DanielJMaher** [comment]
@birdage Does this ignore them, or put them in with a modified name?

**Comment by FBRTMaka** [comment]
@DanielJMaher it just handles the nonconformity better, rather than throwing an error (I'm guessing it was!).  @birdage Looks good, maybe doesn't need the console.log in the first IF statement (dev-ing leftover?) - I like the error console.log though.

**Comment by DanielJMaher** [comment]
We need a formalization of our logging.  We need to get out of print statements and console.logs().  I'm not too worried right now though.  Lets merge this bad boy.  @oceanzus Stand by on dockerizing.  I need to determine if we are patching or if they are correctly populating their records.

**Comment by DanielJMaher** [comment]
Also, @birdage Was this tested against uframe.ooi as well as uframe-test.ooi?

**Pull request merged**
