### PR TITLE
page templates for home, data_catalog, instrument, station

### PR DESCRIPTION
**Pull request by maka-io**
@DanielJMaher , @brian-smith723 , No routes are created yet.  I'm using the more modern approach to organizing template pages by keeping their js, css, and html together in one folder.  This will make working on each file more manageable and lessen the page bleed that is happening with Grunt.

All page template views, models, and partials should live in  their respective page's folders.

### CODE REVIEW

**Comment by oceanzus** [comment]
Can you get rid of the .gitkeep files?  I don't think we want them in there.

**Comment by maka-io** [comment]
@oceanzus the git keep files were to have the folders be pushed.  If you don't add those, empty folders don't get stored in git

But, on second thought I removed those stubbed out folders in lieu of a more component based method;  

e.g.:

home/
    map/
        models/
        views/
        partials/
    left-column/
        models/
        views/
        partials/

More flexible that way.   What do you think?

**Comment by oceanzus** [comment]
Works for me as long as we can keep the grunt file from being insanely complex.

**Comment by maka-io** [comment]
@oceanzus Cool.  I'm hoping this structure will help the grunt file structure as well.  One block per page, and not several blocks to make up one page (as it is now).

**Comment by maka-io** [comment]
@DanielJMaher , @oceanzus making this simpler ... will reopen in a few

**Comment by maka-io** [comment]
@DanielJMaher @oceanzus , Iooks like the gruntfile will get insanely complex.  Here's a more normal fit, and the routes are also added (home, station, instrument, data_catalog).

**Pull request merged**
