### PR TITLE
Canned message text

### PR DESCRIPTION
**Pull request by FBRTMaka**
@DanielJMaher , removed those canned messages.

### CODE REVIEW

**Comment by DanielJMaher** [comment]
@FBRTMaka Does it look for the 3 most recent messages in the OpLog?

Better question, how is it populated

**Comment by FBRTMaka** [comment]
@DanielJMaher , it's just a static json file.  I'm getting familiar with the the full stack of the oplog atm

**Comment by DanielJMaher** [comment]
@FBRTMaka Would it help if I brought Sontag in on this?  We need both the navbar drop down AND the oplog screen fully functional

**Comment by DanielJMaher** [comment]
@FBRTMaka Where are we here?!

**Comment by DanielJMaher** [comment]
@FBRTMaka Email me this weekend if you work on this at all.  I'm not sure if this is a complete PR yet.

**Comment by FBRTMaka** [comment]
@DanielJMaher I'm working on it now, ran into a issue when I just pulled down the last services commits so I have to hash that out...

**Comment by FBRTMaka** [comment]
@DanielJMaher , @lukecampbell : Please review, since the messages feature wasn’t completely implemented it’s been tabled for now in the commit.  Now there is a link that takes you directly to the Operator Logs page.

**Pull request merged**
