### PR TITLE
re organize the map controls and init

### PR DESCRIPTION
**Pull request by birdage**
DONT MERGE YET

### CODE REVIEW

**Comment by birdage** [comment]
@DanielJMaher @Bobfrat review and merge when ready

**Comment by birdage** [comment]
@Bobfrat wait on this a sec

**Comment by birdage** [comment]
@Bobfrat were good, not alot of end times available

**Comment by DanielJMaher** [comment]
@birdage Im confused by your messages.  This is in a holding pattern or G2G?

**Comment by birdage** [comment]
@DanielJMaher G2G

**Pull request merged**
