### PR TITLE
Permissions

### PR DESCRIPTION
**Pull request by Bobfrat**
@DanielJMaher first crack at it. Pull it down and test. This is a work in progress. As is right now, this will prevent users from going to the plotting page and asset management pages without being logged in. It will redirect to the science page

@FBRTMaka fyi

### CODE REVIEW

**Comment by FBRTMaka** [comment]
hey @Bobfrat , this good to go?

**Comment by Bobfrat** [comment]
No let's hold off on this until @DanielJMaher gives it his blessing.

**Comment by birdage** [comment]
@Bobfrat :+1:

**Comment by Bobfrat** [comment]
not sure if that was ready, @DanielJMaher were you able to test this one out?

**Comment by birdage** [comment]
@Bobfrat not sure, @DanielJMaher told me to get through and merge, so i presumed ready.

**Comment by DanielJMaher** [comment]
No this was not ready.  This was my bad... I didn't want you to merge when you reviewed, jsut give the green light. Is it possible to revert?  Or do we need to go in a certain order

**Comment by DanielJMaher** [comment]
@birdage Can we revert ?

**Pull request merged**
