### PR TITLE
Fix annotation update

### PR DESCRIPTION
**Pull request by birdage**

### CODE REVIEW

**Comment by birdage** [comment]
need to fix merge issues

**Comment by birdage** [comment]
@DanielJMaher @FBRTMaka @Bobfrat review please

**Comment by birdage** [comment]
@DanielJMaher as requested it was done before noon!

**Comment by FBRTMaka** [comment]
@birdage , I'm sure this is something you've noticed, but when I go to update an annotation's date the confirm button is still showing as 'add'.

Not a total show stopper for me . . . but if you WANT to fix that before I merge let me know.  Otherwise I've checked that the dates can be changed and it looks good!

screen shot 2015-10-05 at 3 22 52 pm

**Comment by FBRTMaka** [comment]
@birdage going once  . . .

**Comment by birdage** [comment]
merge it and ill fix in another one

**Comment by FBRTMaka** [comment]
@birdage heard that bud!

**Pull request merged**
