### PR TITLE
tidy up status page, based on feedback

### PR DESCRIPTION
**Pull request by birdage**
@DanielJMaher based on feedback

### CODE REVIEW

**Comment by birdage** [comment]
@DanielJMaher @FBRTMaka @Bobfrat review and merge please

**Comment by birdage** [comment]
added roll up for inactive/healthy

**Comment by birdage** [comment]
screen shot 2015-09-30 at 11 00 02 am

screen shot 2015-09-30 at 10 59 58 am

**Comment by birdage** [comment]
screen shot 2015-09-30 at 1 21 31 pm

**Comment by birdage** [comment]
@DanielJMaher @Bobfrat ready

**Comment by FBRTMaka** [comment]
@birdage still a problem here.
screen shot 2015-09-30 at 3 19 25 pm

**Comment by FBRTMaka** [comment]
Cool! Works!

**Pull request merged**
