### PR TITLE
adds ngdc bathy

### PR DESCRIPTION
**Pull request by birdage**
@DanielJMaher adds ngdc bath tile option to the map

### CODE REVIEW

**Comment by birdage** [comment]
@DanielJMaher add marker icons

screen shot 2015-08-03 at 11 25 32 am

**Comment by FBRTMaka** [comment]
nice!

**Comment by birdage** [comment]
screen shot 2015-08-04 at 10 47 14 am

**Comment by birdage** [comment]
adds labels and array icons, requires a `bower install`

**Comment by birdage** [comment]
@DanielJMaher whos the reviewer on this?

**Comment by DanielJMaher** [comment]
@Bobfrat @FBRTMaka @oceanzus Any of these three fine gentlemen

**Comment by DanielJMaher** [comment]
@Bobfrat Ping

**Comment by FBRTMaka** [comment]
@birdage looks good to me!  This ready to go?

**Comment by birdage** [comment]
@FBRTMaka yup!

**Comment by FBRTMaka** [comment]
sweeeet

**Pull request merged**
