### PR TITLE
zooming hides the labels on the map past a certain point

### PR DESCRIPTION
**Pull request by birdage**
updates the popups when zooming

### CODE REVIEW

**Comment by birdage** [comment]
@Bobfrat @DanielJMaher

**Comment by birdage** [comment]
@dlangston this is ready for you to add to the styling task

**Comment by birdage** [comment]
@Bobfrat @DanielJMaher dont merge yet one more thing to add

**Comment by FBRTMaka** [comment]
@birdage good to go?

**Comment by birdage** [comment]
@FBRTMaka yup!

**Pull request merged**
