### PR TITLE
landing-page_inital commit

### PR DESCRIPTION
**Pull request by dlangston**

### CODE REVIEW

**Comment by lukecampbell** [comment]
I will merge this tomorrow. Probably...

**Comment by dlangston** [comment]
Needs backbone integration to use models/partials. TOC needs to reflect the infrastructure page.

**Comment by oceanzus** [comment]
Is there a reason this isn't merged yet?

**Comment by DanielJMaher** [comment]
He is still working it

**Comment by DanielJMaher** [comment]
Should be done soon though

**Comment by DanielJMaher** [comment]
@dlangston YOu overrode this PR with another one right?  I can close this?

**Pull request closed without merging**
